//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyProgrammer291Easy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyProgrammer291Easy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 120
        ///297 90
        ///66 110
        ///257 113
        ///276 191
        ///280 129
        ///219 163
        ///254 193
        ///86 153
        ///206 147
        ///71 137
        ///104 40
        ///238 127
        ///52 146
        ///129 197
        ///144 59
        ///157 124
        ///210 59
        ///11 54
        ///268 119
        ///261 121
        ///12 189
        ///186 108
        ///174 21
        ///77 18
        ///54 90
        ///174 52
        ///16 129
        ///59 181
        ///290 123
        ///248 132.
        /// </summary>
        internal static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 80
        ///30 50
        ///130 75
        ///90 60
        ///150 85
        ///120 70
        ///200 200
        ///110 100.
        /// </summary>
        internal static string TestInputText {
            get {
                return ResourceManager.GetString("TestInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 5.
        /// </summary>
        internal static string TestOutput {
            get {
                return ResourceManager.GetString("TestOutput", resourceCulture);
            }
        }
    }
}
